### ISSUE TITLE
'[ng:app] not a valid selector

### ISSUE THREAD

**Issue by peterktung** [angular/blocking-proxy#36]
I keep getting the following error on my tests:
```
Selenium::WebDriver::Error::WebDriverError:
       unexpected response, code=500, content-type=""
       Error: Error from waitForAngular: Failed to execute 'querySelectorAll' on 'Document': '[ng:app]' is not a valid selector.
```
I removed both `trySelector('[ng:app]')` and `trySelector('[ng:controller]')` in https://github.com/angular/blocking-proxy/blob/master/lib/client_scripts/wait.js#L111, and my tests are working now.

I don't know enough to say if those `trySelector` calls need to be there or not.  But perhaps the method should also be surrounded by a `try-catch` like the `tryEl` method?

**Comment by heathkit** [comment]
Turns out those selectors aren't escaped properly. Are you using BlockingProxy directly, or are you using it through Protractor? Also, is this an AngularJS app? I'm guessing most people haven't hit this code path yet since they tend to either have the app on document.body or are passing a root element.

**Comment by heathkit** [comment]
Turns out this was fixed upstream in Protractor, that's what I get for just copying the client side scripts. https://github.com/angular/protractor/pull/4021

**Comment by peterktung** [comment]
Thanks for the quick turnaround!  I'm using Blocking Proxy directly, and I only have the `ng-controller`directive for a widget.
